app:
    resource: @AppBundle/Controller/
    type:     annotation

user:
    resource: @UserBundle/Controller/
    type:     annotation
    prefix:   /

fos_user:
    resource: @FOSUserBundle/Resources/config/routing/all.xml

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"